name: Publish

on:
  push:
    tags: [ v* ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Use .NET SDK
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: 10.0.x

    - name: NuGet login
      uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
      id: login
      with:
        user: shibayan

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Pack NuGet Packages
      run: |
        dotnet pack src/WebJobs.Extensions.HttpApi/WebJobs.Extensions.HttpApi.csproj -c Release -o ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}
        dotnet pack src/Worker.Extensions.HttpApi/Worker.Extensions.HttpApi.csproj -c Release -o ./dist -p:Version=${{ steps.setup_version.outputs.VERSION }}

    - name: Publish NuGet Packages
      run: dotnet nuget push dist/*.nupkg -k ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
